apiVersion: v1
kind: Service
metadata:
  name: k8s-beginner-demo-svc
  namespace: demo-app
  labels:
    app: k8s-beginner-demo
spec:
  type: NodePort
  selector:
    app: k8s-beginner-demo
  ports:
    - name: http
      port: 80          # Service port
      targetPort: 5000  # Container port
      nodePort: 30081   # Optional fixed node port (must be between 30000-32767)
